<?php
/**
 * @file
 * ALterations for the events site.
 */

/**
 * Implements hook_block_info().
 */
function conditional_content_block_block_info() {
  $blocks['conditional'] = array(
    'info' => t('Conditional Text Block'),
    'description' => t('A block with text message based upon role.'),
  );
  return $blocks;
}

/**
 * Implements hook_block_configure().
 */
function conditional_content_block_block_configure($delta = '', $settings = array()) {
  $form = array();
  if ($delta == 'conditional') {
    $roles = user_roles();
    $settings += array(
      'ccb_first_message' => array(
        'value' => 'Default First Message.',
      ),
      'ccb_second_message' => array(
        'value' => 'Default Second Message.',
      )
    );
    $form['ccb_title'] = array(
      '#type' => 'textfield',
      '#title' => t('The title for your block.'),
      '#default_value' => $settings['ccb_title'],
    );
    $form['ccb_first_role'] = array(
      '#type' => 'select',
      '#title' => 'First role',
      '#options' => $roles,
      '#default_value' => $settings['ccb_first_role'],
    ); 
    $form['ccb_first_message'] = array(
      '#type' => 'text_format',
      '#title' => t('First text'),
      '#default_value' => $settings['ccb_first_message']['value'],
      '#description' => 'Provide text for unauthenticated users or site visitors.',
      '#format' => $settings['ccb_first_message']['format'],
      '#editor_uploads' => TRUE,
      '#rows' => 8,
    );
    $form['ccb_second_role'] = array(
      '#type' => 'select',
      '#title' => 'Second role',
      '#options' => $roles,
      '#default_value' => $settings['ccb_second_role'],
    ); 
    $form['ccb_second_message'] = array(
      '#type' => 'text_format',
      '#title' => t('Second text'),
      '#default_value' => $settings['ccb_second_message']['value'],
      '#description' => 'Provide text for authenticated users.',
      '#format' => $settings['ccb_second_message']['format'],
      '#editor_uploads' => TRUE,
      '#rows' => 8,
    );
  }
  return $form;
}

/**
 * Implements hook_block_view().
 */
function conditional_content_block_block_view($delta = '', $settings = array(), $contexts = array()) {
  global $user;
  switch ($delta) {
    case 'conditional':
      $block = array();
      $first_role = check_plain($settings['ccb_first_role']);
      $second_role = check_plain($settings['ccb_second_role']);
      $block_first_text = $settings['ccb_first_message'];
      $block_second_text = $settings['ccb_second_message'];
      $block_first_message = filter_xss_admin($block_first_text['value']);
      $block_second_message = filter_xss_admin($block_second_text['value']);
      $title = t('Next Steps');
      foreach ($user->roles as $role) {
        if ($role == $first_role) {
          $markup .= $block_first_message;
        } elseif ($role == $second_role) {
          $markup .= $block_second_message;
        }
        if ($first_role == $role || $second_role == $role) {
          $block_title = check_plain($settings['ccb_title']);
        }
      }
      $block['subject'] = $block_title;
      $block['content'] = array(
        '#type' => 'markup',
        '#markup' => $markup,
      );
      break;
    }
  return $block;
}
